name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - name: Build with Maven
        run: mvn -e --batch-mode clean install
